### ISSUE TITLE
resume interrupted process

### ISSUE THREAD

**Issue by yangyuneteng** [mirror/mirror#19] opened 2015-07-12 06:21 UTC
SVN is so slow and if for some reason the script dies, I am unable to resume the process.

$ git svn rebase
fatal: bad revision 'HEAD'
rev-list --first-parent --pretty=medium HEAD --: command returned error: 128

$ git push
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>

**Comment by john-peterson** [comment] 2015-07-12 08:20
first focus on cloning the whole repo. ive used these commands to force it to fix or resume it

	git checkout -f
	rm -r .git/svn
	git svn fetch
	git svn rebase

**Comment by realdreams** [comment] 2015-07-13 15:40
after successful git svn fetch

$ git status    
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/linux/universal/linux-3.10/include/linux/platform_data/phy-at803x.h
        src/linux/universal/linux-3.18/3.18-rc4.diff


$ git svn rebase
First, rewinding head to replay your work on top of it...
Killed
could not detach HEAD
rebase refs/remotes/git-svn: command returned error: 1

always fails here.


I don't know where those 2 files come from, even if I delete them git svn rebase still fails with the same error

**Comment by john-peterson** [comment] 2015-07-13 16:23
print the top commit

	git log -1

**Comment by realdreams** [comment] 2015-07-13 16:55
$ git log -1
commit 60da7944be015f680946a7b38492be65f1e1596d
Author: BrainSlayer <BrainSlayer@52c4871e-980c-0410-b1e0-e73912ce01f8>
Date:   Sat Mar 28 12:32:57 2015 +0000

    just missed that
    
    git-svn-id: svn://svn.dd-wrt.com/DD-WRT@26601 52c4871e-980c-0410-b1e0-e73912ce01f8

**Comment by john-peterson** [comment] 2015-07-13 17:12
so close fuk. try these commands again https://github.com/mirror/mirror/issues/19#issuecomment-120700915

**Comment by realdreams** [comment] 2015-07-13 17:17
I have tried it several times. The last commit is from git pull (the same as https://github.com/mirror/dd-wrt/ )

**Comment by john-peterson** [comment] 2015-07-13 17:22
dont pull in that it wil fuk it up

**Comment by realdreams** [comment] 2015-07-13 17:25
There would be no local branch if I don't pull (can't do svn rebase). issue #20

**Comment by john-peterson** [comment] 2015-07-13 17:26
u fuked it up bro. start over

	git svn clone svn://svn.dd-wrt.com/DD-WRT .

**Comment by realdreams** [comment] 2015-07-16 14:46
$ git log --grep=26601
commit 6f04f4d936975b54ef4709a64965c7c4ab13f272
Author: BrainSlayer <BrainSlayer@52c4871e-980c-0410-b1e0-e73912ce01f8>
Date:   Sat Mar 28 12:32:57 2015 +0000

    just missed that
    
    git-svn-id: svn://svn.dd-wrt.com/DD-WRT@26601 52c4871e-980c-0410-b1e0-e73912ce01f8

$ git push --set-upstream origin master
To git@github.com:mirror/dd-wrt.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:mirror/dd-wrt.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git died so many times during svn fetch, finally I have the entire repository. However the hash I have are different than those already on github. The last hash for r26601 is 60da7944be015f680946a7b38492be65f1e1596d on github. I am unable to push.

**Comment by john-peterson** [comment] 2015-07-16 14:53
it should be diff. all git svn clone make diff hashes. force push it

	git push -f

**Closed** 2016-01-12 21:45 UTC
